#!/bin/bash

echo "Starting workers for traversal test"


KIBITZ_ROLE=ROOT GLOG_log_dir=log GLOG_minloglevel=0 ./src/regression-tester -I1 -Ttest_worker_a -b'tcp://localhost:5556' -d'tcp://localhost:5557' -p9000 -P9100 & 
KIBITZ_ROLE=CHILD GLOG_log_dir=log GLOG_minloglevel=0 ./src/regression-tester -I1 -Ttest_worker_b -b'tcp://localhost:5556' -d'tcp://localhost:5557' -p9001 -P9101 -ftest/traversal/test-worker-b.yaml &
KIBITZ_ROLE=CHILD GLOG_log_dir=log GLOG_minloglevel=0 ./src/regression-tester -I1 -Ttest_worker_c -b'tcp://localhost:5556' -d'tcp://localhost:5557' -p9002 -P9102 -ftest/traversal/test-worker-c.yaml &
KIBITZ_ROLE=CHILD GLOG_log_dir=log GLOG_minloglevel=0 ./src/regression-tester -I1 -Ttest_worker_d -b'tcp://localhost:5556' -d'tcp://localhost:5557' -p9003 -P9103 -ftest/traversal/test-worker-d.yaml &

echo "wait 5 seconds for heartbeats to perculate throughout system"
sleep 5 
echo "Workers started establishing collaboration connections and running jobs"

ruby script/setup-collaboration.rb 'tcp://localhost:5556'
sleep 5 
ruby script/start-collaboration.rb 'tcp://localhost:5556'
ruby script/shutdown-workers.rb 'tcp://localhost:5556'




